trigger:
  - main

variables:
  vmImageName: 'vs2017-win2016'

stages:
  - stage: Plan Stage
    displayName: Plan Stage

    jobs:
      - job: Plan
        displayName: 'Plan MyHealth.API.Activity Infrastructure'
        pool:
          vmImage: $(vmImageName)
      
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Terraform files to artifacts'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/_willvelida_velidaazureengine/services/myhealth-api-activity'
            TargetFolder: '$(build.artifactstagingdirectory)'
            
        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
          displayName: 'Use Terraform 0.12.24'
          inputs:
            terraformVersion: 0.12.24

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: 'terraform init'
          inputs:
            command: init
            workingDirectory: '$(System.DefaultWorkingDirectory)/_willvelida_velidaazureengine/services/myhealth-api-activity'
            backendType: azurerm
            backendServiceArm: azureConnectionName
            backendAzureRmResourceGroupName: velidarg
            backendAzureRmStorageAccountName: velidaterraform
            backendAzureRmContainerName: myhealthapiactivitytfstate
            backendAzureRmKey: terraform.tfstate

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: 'terraform validate'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/_willvelida_velidaazureengine/services/myhealth-api-activity'

        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
          displayName: 'terraform plan'
          inputs:
            command: plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/_willvelida_velidaazureengine/services/myhealth-api-activity'
            environmentServiceName: azureConnectionName
          